In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
l = [1,2,3]
print(l)

[1, 2, 3]


In [3]:
def square(x):
    return x*x
print(square(5))

25


In [4]:
for i in range(3):
    print(i)


0
1
2


In [5]:
%load_ext watermark

In [6]:
%watermark -v -iv -p numpy,pandas,matplotlib

Python implementation: CPython
Python version       : 3.14.2
IPython version      : 9.9.0

numpy     : 2.4.1
pandas    : unknown
matplotlib: unknown



In [7]:
def python_forloop_list_approach(x, w):
    z = 0.
    for i in range(len(x)):
        z += x[i] * w[i]
    return z


a = [1., 2., 3.]
b = [4., 5., 6.]

print(python_forloop_list_approach(a, b))

32.0


In [8]:
large_a = list(range(1000))
large_b = list(range(1000))


%timeit python_forloop_list_approach(large_a, large_b)

126 μs ± 3.33 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
import numpy as np


def numpy_dotproduct_approach(x, w):
    # same as np.dot(x, w)
    # and same as x @ w
    return x.dot(w)
    

a = np.array([1., 2., 3.])
b = np.array([4., 5., 6.])

print(numpy_dotproduct_approach(a, b))

32.0


In [10]:
large_a = np.arange(1000)
large_b = np.arange(1000)

%timeit numpy_dotproduct_approach(large_a, large_b)

2.25 μs ± 73.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
a=[1,2,3]
type(a)

list

In [12]:
np.array(a)
type(np.array(a))

numpy.ndarray

In [13]:
lst = [[1,2,3],[4,5,6]]
arr = np.array(lst)
print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.ndim

2

In [16]:
arr.shape

(2, 3)

In [17]:
np.ones((2,3), dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
np.zeros((4,4), dtype=np.float32)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [19]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [20]:
a = np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [21]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
print(lst)

[[1, 2, 3], [4, 5, 6]]


In [23]:
lst[1,2]

TypeError: list indices must be integers or slices, not tuple

In [ ]:
arr[0,2]

np.int64(3)

In [ ]:
arr+4

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.add(arr,4)

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
np.power(arr, 2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
arr.sum(axis=0) # sum of each column
arr.sum(axis=1) # sum of each row

array([ 6, 15])

In [ ]:
np.random.seed(0)
a=np.random.rand(3)
print(a)

[0.5488135  0.71518937 0.60276338]


In [ ]:
a.shape

(3, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
p=arr.ravel()

In [ ]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
p.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
p.reshape(-1,2) # -1 basically fills in to fit based on the other value

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate([arr,arr], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
p

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.where(p>3)

(array([3, 4, 5]),)

In [ ]:
row_vector = np.array([1,2,3])
row_vector.shape

(3,)

In [ ]:
np.dot(arr, row_vector)

array([14, 32])

In [ ]:
column_vector = np.array([1,2,3]).reshape(-1,1)

In [ ]:
arr.dot(column_vector)

array([[14],
       [32]])

In [ ]:
np.dot(arr,column_vector)

array([[14],
       [32]])

In [ ]:
arr @ column_vector

array([[14],
       [32]])

In [ ]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])